Проект 9го спринта.
yandex-praktikum/java-filmorate pull request #46
Opened 2022-11-17 10:22 UTC by AlexandraLesnykh

2022-11-17 22:15 UTC, db-exp requested changes

2022-11-17 22:15 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/ValidatorTest.java
> +public class ValidatorTest {
Кажется, съехало форматирование

2022-11-17 22:15 UTC, db-exp commented on pom.xml
> +			<artifactId>spring-boot-starter-data-rest</artifactId>
а зачем data-rest?

2022-11-17 22:15 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Давай добавим NonNull на поля, которые надо заполнить?

2022-11-17 22:15 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Давай добавим NonNull на поля, которые надо заполнить?

2022-11-18 08:34 UTC, AlexandraLesnykh commented on pom.xml
> +			<artifactId>spring-boot-starter-data-rest</artifactId>
При создании проекта в Spring Initializr  добавила, думала вдруг пригодится. Убрать забыла)

2022-11-19 12:04 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Добавила.

2022-11-19 12:04 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Добавила.

2022-11-19 18:49 UTC, AlexandraLesnykh commented
Внесены изменения в логику валидации.

2022-11-20 06:24 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public User(int id, Optional<String> name, @UserValid LocalDate birthday, @NonNull String email, @NonNull String login) {
Вместо UserValid можно использовать PastOrPresent

2022-11-20 06:48 UTC, db-exp requested changes

2022-11-20 06:48 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/UserValidator.java
> +        return user.getBirthday().isAfter(LocalDate.now());
день рождения же не может быть только в будущем)

2022-11-20 06:48 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/UserValidator.java
> +        return user.getBirthday().isAfter(LocalDate.now());
Класс будет работать правильно если сделать так

public class UserValidator implements ConstraintValidator<UserValid, LocalDate> {


    @Override
    public void initialize(UserValid birthday) {
    }
    @Override
    public boolean isValid(LocalDate birthday, ConstraintValidatorContext constraintValidatorContext) {
        return birthday.isBefore(LocalDate.now());
    }
}

и в модели аннотацию повесить на поле birthday
Тогда при вызове контроллера будет честная ошибка 400 и сообщение

 [Field error in object 'user' on field 'birthday': rejected value [2026-08-20]; codes [UserValid.user.birthday,UserValid.birthday,UserValid.java.time.LocalDate,UserValid]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.birthday,birthday]; arguments []; default message [birthday]]; default message [error user birthday]] ]

2022-11-20 06:48 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/FilmValidator.java
> +    public boolean isValid(Film film, ConstraintValidatorContext constraintValidatorContext) {
тут та же проблема, что и в UserValidator

2022-11-20 06:48 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +  //  @FilmValid
вот тут FilmValid - правильно было
Как легко проверить - запустить приложение, открыть postman и вызвать для POST localhost:8080/films
{
    "name": "nisi eiusmod",
    "description": "adipisicing",
    "releaseDate": "1727-03-25",
     "duration": 100
   }
и 
{
    "name": "nisi eiusmod",
    "description": "adipisicing",
    "releaseDate": "1927-03-25",
     "duration": 100
   }
Смысл валидации вернуть ошибку 400 Bad request, а не упасть с 500)

2022-11-20 12:24 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public User(int id, Optional<String> name, @UserValid LocalDate birthday, @NonNull String email, @NonNull String login) {
Сделано.

2022-11-20 12:25 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/UserValidator.java
> +        return user.getBirthday().isAfter(LocalDate.now());
Сделано.
Дмитрий, спасибо за комментарии! Они мотивируют двигаться дальше! :)

2022-11-20 12:25 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/FilmValidator.java
> +    public boolean isValid(Film film, ConstraintValidatorContext constraintValidatorContext) {
Исправлено.

2022-11-20 12:26 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +  //  @FilmValid
Исправлено.

2022-11-20 12:26 UTC, AlexandraLesnykh commented
Новая итерация проекта 9го спринта.  Внесены изменения в Film&User Validator, в модели.

2022-11-20 13:49 UTC, db-exp requested changes

2022-11-20 13:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +   @PastOrPresent @UserValid
Извини, я тебя, кажется, запутал - нужно был оставить либо твою аннотацию,  либо PastOrPresent - они равноценны и еще сделать формат кода)

2022-11-20 17:41 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +   @PastOrPresent @UserValid
Моя вина, могла бы сама догадаться. Исправлено.

2022-11-20 17:41 UTC, AlexandraLesnykh commented
[Удалена аннотация, Сделан реформат кода

2022-11-20 23:14 UTC, db-exp approved these changes

2022-11-21 06:34 UTC, yandex-praktikum commented
Работа сдается только в личном репозитории.
Закрываю.

2022-11-21 06:34 UTC, closed without merging